### ISSUE TITLE
dependency on retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [maoguihu/atakrig#5]
Email April 11:

The next blog has appeared:
https://r-spatial.org/r/2023/04/10/evolution3.html.

It is now time to take action. As a minimum, move rgeos from Imports to
Suggests. Actually, neither rgeos nor rgdal are used in atakrig at all,
because as I pointed out in December, raster now uses terra (which attakrig
should probably suggest) instead of rgeos and rgdal.

You have, however, at least:

$ grep rgeos atakrig/*/*
grep: atakrig/inst/extdata: Is a directory
atakrig/R/preparation.r:  centxy <- rgeos::gCentroid(x, byid = TRUE)
$ grep rgdal atakrig/*/*
atakrig/demo/runoff.r:library(rgdal)
grep: atakrig/inst/extdata: Is a directory
atakrig/man/ataKriging.Rd:library(rgdal)
atakrig/man/deconvPointVgm.Rd:library(rgdal)
atakrig/R/preparation.r:    gd <- rgdal::putRasterData(x@file@transient, v,
band=1, offset=start-1)

uses of rgeos and rgdal shown by CMD check when rgdal and rgeos are dropped
completely (as they should be). Since NAMESPACE didn't import the packages,
that use was wrong anyway. writeValuesBlock() and discretizePolygon() need
re-writing, probably best using terra. Note that your use of @ to set and
access slots was always risky and fragile.

You seem to have this single point of contact, so if you do not respond to
this message, I will understand that you are happy to abandon atakrig when
rgeos and rgdal are archived (some maintainers do make this choice).

On Thu, 15 Dec 2022, Roger Bivand wrote:

> Dear Maintainer,
>
> atakrig depends on (depends, imports or suggests) **raster** and one or
> more of the retiring packages **rgdal**, **rgeos** or **maptools**
> (https://r-spatial.org/r/2022/04/12/evolution.html,
> https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster**
> `3.6.3`, all use of external FOSS library functionality has been
> transferred to **terra**, making the retiring packages very likely
> redundant. It would help greatly if you could remove dependencies on the
> retiring packages as soon as possible.

Please fix best by June, latest October 2023.

**Comment by rsbivand** [comment]
Tme to update now @maoguihu , response requested urgently.

**Comment by nikosGeography** [comment]
I'd like to ask if you had any updates regarding the use of terra in atakrig.

**Comment by maoguihu** [comment]
Thanks very much for your mind. We are updating the package. However, since we don't formiliar with terra very well, it maybe still require several days.-------- 原始邮件 --------发件人： Nikolaos Tziokas ***@***.***>日期： 2023年6月22日周四 21:35收件人： maoguihu/atakrig ***@***.***>抄送： "MG.Hu" ***@***.***>, Mention ***@***.***>主    题： Re: [maoguihu/atakrig] dependency on retiring spatial infrastructure packages (Issue #5)
I'd like to ask if you had any updates regarding the use of terra in atakrig.

**Comment by rsbivand** [comment]
@maoguihu Only three months remain to submit the updates to CRAN. Maybe create a branch and invite @nikosGeography to help in migrating your package?

**Comment by nikosGeography** [comment]
> @maoguihu Only three months remain to submit the updates to CRAN. Maybe create a branch and invite @nikosGeography to help in migrating your package?

I could help if needed but I have no experience in building a package. But as I said, I would be more than happy to contribute in any way I can.

**Comment by rsbivand** [comment]
@maoguihu Less than three weeks remain to fix this.

**Comment by rsbivand** [comment]
@maoguihu R spatial infrastructure packages maptools, rgdal and rgeos will be archived by CRAN on Monday, October 16, 2023. Your package does not pass CMD check when these packages are not available. Expect your package to be archived by CRAN October 17-18 as CRAN checks feed through and your package fails, if not updated by Monday, October 16, 2023. 

No grace period is anticipated, as you have had sufficient time to update your package to remove dependencies on maptools, rgdal and/or rgeos. It remains the case that many packages importing the raster package needlessly depend on retiring packages, as raster stopped using them a year ago.

**Comment by nikosGeography** [comment]
I just tried the function `discretizeRaster` using a `rast` variable (i.e., from `terra` package) and it worked. Thank you.

**Comment by maoguihu** [comment]
Thanks.
 


Maogui
 
From: Nikolaos Tziokas
Date: 2023-10-10 18:38
To: maoguihu/atakrig
CC: MG.Hu; Mention
Subject: Re: [maoguihu/atakrig] dependency on retiring spatial infrastructure packages (Issue #5)
I just tried the function discretizeRaster using a rast variable (i.e., from terra package) and it worked. Thank you.

**Comment by rsbivand** [comment]
0.9.8.1 OK, thank you for your cooperation!
